systems:
  NES:
    emulator_path: "C:\\RetroArch-Win64\\retroarch.exe"
    launch_arguments: '-L C:\RetroArch-Win64\cores\fceumm_libretro.dll {rom_path}'
    paths:
      - "C:\\Torrents\\Games\\NES"
  SNES:
    emulator_path: "C:\\RetroArch-Win64\\retroarch.exe"
    launch_arguments: '-L C:\RetroArch-Win64\cores\snes9x_libretro.dll {rom_path}'
    paths:
      - "C:\\Torrents\\Games\\SNES"
  Arcade:
    emulator_path: "C:\\Emulation\\Emulators\\MAME\\mame.exe"
    launch_arguments: '-inipath C:\Emulation\Emulators\MAME\ {rom_path}'
    start_in: "C:\\Emulation\\Emulators\\MAME"
    paths:
      - "C:\\Torrents\\Games\\Arcade\\MAME 0.270 ROMs (split)"
  N64:
    emulator_path: "C:\\RetroArch-Win64\\retroarch.exe"
    launch_arguments: '-L C:\RetroArch-Win64\cores\mupen64plus_next_libretro.dll {rom_path}'
    paths:
      - "C:\\Torrents\\Games\\N64"
  DS:
    emulator_path: "C:\\RetroArch-Win64\\retroarch.exe"
    launch_arguments: '-L C:\RetroArch-Win64\cores\melondsds_libretro.dll {rom_path}'
    paths:
      - "C:\\Torrents\\Games\\DS"
  GBA:
    emulator_path: "C:\\RetroArch-Win64\\retroarch.exe"
    launch_arguments: '-L C:\RetroArch-Win64\cores\mgba_libretro.dll {rom_path}'
    paths:
      - "C:\\Torrents\\Games\\GBA"
  PS1:
    emulator_path: "C:\\Emulation\\Emulators\\Duckstation\\duckstation-nogui-x64-ReleaseLTCG.exe"
    launch_arguments: '{rom_path}'
    paths:
      - "C:\\Emulation\\ROMs\\Sony - PlayStation"
  MD:
    emulator_path: "C:\\RetroArch-Win64\\retroarch.exe"
    launch_arguments: '-L C:\RetroArch-Win64\cores\genesis_plus_gx_libretro.dll {rom_path}'
    paths:
      - "C:\\Torrents\\Games\\MD"